mt6625l: fix error: expected declaration specifiers
drivers/misc/mediatek/connectivity/wlan/gen2/os/version.h:133:20:
error: expected declaration specifiers or '...' before string constant
  133 | #define NIC_NAME   "MT6582"
      |                    ^~~~~~~~
drivers/misc/mediatek/connectivity/wlan/gen2/os/linux/gl_init.c:3523:25:
note: in expansion of macro 'NIC_NAME'
 3523 | MODULE_SUPPORTED_DEVICE(NIC_NAME);

Fixes: 6417f03132a6 ("module: remove never implemented MODULE_SUPPORTED_DEVICE")